version: "3"
services:
    handmades-server:
        container_name: handmades-server
        image: handmades_node
        ports:
          - "8042:8042"
          - "8043:8043"
        links:
          - mongo
    mongo:
        container_name: mongo_handmades
        image: mongo
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
        ports:
          - '27017:27017'
