version: "3"
services:
    handmades-server:
        container_name: handmades-server
        image: handmades_node
        ports:
          - "8042:8042"
          - "8043:8043"
        links:
          - "mongo:mongodb"
    mongo:
        container_name: mongo_handmades
        image: handmades_mongo
        ports:
          - '27017:27017'
